In [1]:
import requests
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup as bs
from random import randint
import itertools as it
import mysql.connector

In [2]:
r = requests.get('https://www.pichau.com.br/hardware/ssd')

print(r.status_code)

200

In [3]:
html = r.text
soup = bs(html)

In [4]:
with open("html_txt.html", "w", encoding="utf-8") as f:
    f.write(r.text)

In [5]:
products = soup.find_all('h2')
products_list = []
for i in products:
    txt = i.get_text()
    products_list.append(txt)

print(products_list[0:5])

['SSD Duex Red Series DX SSD240N, 240GB, 2.5", Sata III 6GB/s, Leitura 500 MB/s, Gravacao 420 MB/s, DX SSD240N',
 'SSD WD Red, 1TB, 2.5", Sata III 6 Gb/s, Leitura 560Mb/s, Gravacao 530Mb/s, WDS100T1R0A',
 'SSD Lexar NM610, 1TB, M.2 2280, PCIe NVMe, Leitura 2100 MB/s, Gravacao 1600 MB/s, LNM610-1TRBNA',
 'SSD Lexar NM610, 500GB, M.2 2280, PCIe NVMe, Leitura 2100 MB/s, Gravacao 1600 MB/s, LNM610-500RBNA',
 'SSD Externo Adata SD600Q, 480GB, SATA, Leitura 440MB/s, Gravacao 440MB/s, ASD600Q-480GU31-CBK',
 'SSD Adata Legend 840, 512GB, M.2 2280, PCIe NVMe, Leitura 5000 MB/s, Gravacao 4500 MB/s, ALEG-840-512GCS',
 'SSD Adata Legend 750, 1TB, M.2 2280, PCIe NVMe, Leitura 3500 MB/s, Gravacao 3000 MB/s, ALEG-750-1TCS',
 'SSD Adata Legend 750, 500GB, M.2 2280, PCIe NVMe, Leitura 3500 MB/s, Gravacao 3000 MB/s, ALEG-750-500GCS',
 'SSD Kingston KC3000, 512GB, M.2 2280, PCIe NVMe, Leitura 7000 MB/s, Gravacao 3900 MB/s, SKC3000S/512G',
 'SSD Lexar NQ100, 960GB, 2.5, Sata III 6GB/s, Leitura 550 MB/s, Gravacao 500MB/s, LNQ100X960G-RNNNU',
 'SSD Adata XPG Gammix S50 Lite, 2TB, M.2 2280, PCIe NVMe, Leitura 3900 MB/s, Gravacao 3200 MB/s, AGAMMIXS50L-2T-CS',
 'SSD Externo Adata SD600Q, 960GB, SATA, Leitura 440MB/s, Gravacao 440MB/s, ASD600Q-960GU31-CBK',
 'SSD Externo Adata SD600Q, 240GB, SATA, Leitura 440MB/s, Gravacao 440MB/s, ASD600Q-240GU31-CBK',
 'SSD Adata SU635, 240GB, SATA III 6GB/s, Leituras 520MB/s, Gravacao 450MB/s, ASU635SS-240GQ-R',
 'SSD Adata SU635, 480GB, SATA III 6GB/s, Leituras 520MB/s, Gravacao 450MB/s, ASU635SS-480GQ-R',
 'SSD WD Black SN850, 2TB, M.2 2280, PCIe NVMe, Leitura 7000 MB/s, Gravacao 5100MB/s, WDS200T1XHE',
 'SSD WD Green SN350, 2TB, M.2 2280, PCIe NVMe, Leitura 3200 MB/s, Gravacao 3000 MB/s, WDS200T3G0C',
 'SSD WD Blue SN550, 2TB, M.2 2280, PCIe NVMe, Leitura 2600 MB/s, Gravacao 1800 MB/s, WDS200T2B0C',
 'SSD WD Blue, 4TB, 2.5, Sata III 6GB/s, Leitura 560 MB/s, Gravacao 530 MB/s, WDS400T2B0A',
 'SSD Kingston NV1, 1TB, M.2 2280, PCIe NVMe, Leitura 2100 MB/s, Gravacao 1700 MB/s, SNVS/1000G',
 'SSD Kingston NV1, 500GB, M.2 2280, PCIe NVMe, Leitura 2100 MB/s, Gravacao 1700 MB/s, SNVS/500G',
 'SSD Kingston NV1, 250GB, M.2 2280, PCIe NVMe, Leitura 2100 MB/s, Gravacao 1100 MB/s, SNVS/250G',
 'SSD Team Group CX2, 2TB, 2.5, Sata III 6GB/s, Leitura 540 MB/s, Gravacao 490 MB/s, T253X6002T0C101',
 'SSD MSI Spatium M480, 1TB, M.2 2280, PCIe NVMe, Leitura 7000 MB/s, Gravacao 5500 MB/s, SM480N1TB',
 'SSD MSI Spatium M470, 2TB, M.2 2280, PCIe NVMe, Leitura 5000 MB/s, Gravacao 4400 MB/s, SM470N2TB',
 'SSD MSI Spatium M470, 1TB, M.2 2280, PCIe NVMe, Leitura 5000 MB/s, Gravacao 4400 MB/s, SM470N1TB',
 'SSD MSI Spatium M370, 2TB, M.2 2280, PCIe NVMe, Leitura 2400 MB/s, Gravacao 1850 MB/s, SM370N2TB',
 'SSD MSI Spatium M370, 1TB, M.2 2280, PCIe NVMe, Leitura 2400 MB/s, Gravacao 1750 MB/s, SM370N1TB',
 'SSD MSI M470, 1TB, M.2 2280, PCIe NVMe, Leitura 5000 MB/s, Gravacao 4400 MB/s, M470N1TB OEM',
 'SSD MSI M372, 512GB, M.2 2280, PCIe NVMe, Leitura 2250 MB/s, Gravacao 1850 MB/s, M372N512 OEM',
 'SSD MSI M370, 1TB, M.2 2280, PCIe NVMe, Leitura 2400 MB/s, Gravacao 1750 MB/s, M370N1TB OEM',
 'SSD PNY CS2130, 8TB, M.2 2280, PCIe NVMe, Leitura 3500 MB/s, Gravacao 3000 MB/s, M280CS2130-8TB-RB',
 'SSD PNY XLR8 CS3030, 4TB, M.2 2280, PCIe NVMe, Leitura 3500 MB/s, Gravacao 3100 MB/s, M280CS3030-4TB-RB',
 'SSD PNY XLR8 CS3140, 2TB, M.2 2280, PCIe NVMe, Leitura 7500 MB/s, Gravacao 6850 MB/s, M280CS3140-2TB-RB',
 'SSD PNY XLR8 CS2311, 2TB, 2.5, Sata III 6GB/s, Leitura 560 MB/s, Gravacao 530 MB/s, SSD7CS2311-2TB-RB',
 'SSD PNY XLR8 CS2311, 250GB, 2.5, Sata III 6GB/s, Leitura 560 MB/s, Gravacao 530 MB/s, SSD7CS2311-250-RB']

In [6]:
prices = soup.find_all('div', class_='jss69')
prices_list = []
for p in prices:
    value = p.get_text()
    prices_list.append(value)

print(prices_list[0:5])

['R$269,90',
 'R$1.449,90',
 'R$799,93',
 'R$359,91',
 'R$575,61',
 'R$701,62',
 'R$949,08',
 'R$510,15',
 'R$1.058,04',
 'R$849,96',
 'R$1.590,05',
 'R$1.183,61',
 'R$439,01',
 'R$249,91',
 'R$399,92',
 'R$3.399,90',
 'R$1.799,90',
 'R$1.609,90',
 'R$4.399,90',
 'R$859,98',
 'R$375,01',
 'R$289,91',
 'R$1.899,06',
 'R$2.289,97',
 'R$3.696,99',
 'R$1.849,96',
 'R$2.599,08',
 'R$1.299,04',
 'R$1.879,96',
 'R$699,02',
 'R$1.299,04',
 'R$8.000,16',
 'R$6.284,47',
 'R$4.344,78',
 'R$2.860,14',
 'R$449,01']

In [7]:
prices = soup.find_all('div', class_='jss64')
prices_list = []
for p in prices:
    value = p.get_text()
    prices_list.append(value)

print(prices_list)

[]

In [8]:
urls = ['https://www.pichau.com.br/hardware/processadores/amd', 
        'https://www.pichau.com.br/hardware/processadores/intel',
        'https://www.pichau.com.br/hardware/placa-m-e',
        'https://www.pichau.com.br/hardware/memorias',
        'https://www.pichau.com.br/hardware/placa-de-video',
        'https://www.pichau.com.br/hardware/hard-disk-e-ssd',
        'https://www.pichau.com.br/hardware/ssd',
        'https://www.pichau.com.br/hardware/gabinete',
        'https://www.pichau.com.br/hardware/fonte',
        'https://www.pichau.com.br/perifericos/teclado',
        'https://www.pichau.com.br/perifericos/fone-de-ouvido',
        'https://www.pichau.com.br/perifericos/mouse',
        'https://www.pichau.com.br/monitores']

pichau_products_list = []

for page in urls:
    category = page.split('/')[-1]

    r = requests.get(page)
    print(r.status_code)
    html = r.text

    soup = bs(html)

    products = soup.find_all('h2')
    products_list = []
    for i in products:
        txt = i.get_text()
        products_list.append(txt)
    
    localiz = 'R$' in soup.find_all('div', class_='jss69')[0]

    if localiz:
        prices = soup.find_all('div', class_='jss69')
        prices_list = ['X'] * len(products_list)
        for idx, p in enumerate(prices):
            value = p.get_text()
            prices_list[idx] = value
    else:
        prices = soup.find_all('div', class_='jss64')
        prices_list = ['X'] * len(products_list)
        for idx, p in enumerate(prices):
            value = p.get_text()
            prices_list[idx] = value
    
    category_list = [category] * len(products_list)

    p = {'name': products_list, 'category': category_list, 'price': prices_list}

    df = pd.DataFrame(data=p)

    pichau_products_list.append(df)

products = pd.concat(pichau_products_list).reset_index(drop=True)

200
200
200
200
200
200
200
200
200
200
200
200
200

                                                  nome  categoria        preco
0    Processador AMD Ryzen 5 PRO 4650G, 6-Core, 12-...        amd   R$1.599,90
1    Processador AMD Athlon Silver PRO 3125GE, 2-Co...        amd     R$699,90
2    Processador AMD Ryzen 3 PRO 4350G, 4-Core, 8-T...        amd   R$1.199,00
3    Processador AMD Ryzen Threadripper PRO 3995WX,...        amd  R$35.399,91
4    Processador AMD Ryzen 7 5700G, 8-Core, 16-Thre...        amd   R$2.042,90
..                                                 ...        ...          ...
463  Monitor Gamer Asus Tuf 31,5'' Curvo 1ms 144Hz ...  monitores   R$3.500,02
464  Monitor Gamer Asus Tuf 23,8'' Full HD 1ms 144H...  monitores   R$2.139,07
465  Monitor Gamer Asus 24'' Full HD 0.5ms 165hz G-...  monitores   R$1.989,06
466  Monitor Gamer Asus 23,8'' LED 1ms 144hz Ips Fr...  monitores   R$1.849,96
467  Monitor Gamer Asus 27 Pol. 5ms 75Hz FreeSync H...  monitores   R$2.169,07

[468 rows x 3 columns]

In [9]:
products['price'].replace(to_replace=r"\.", value='', inplace=True, regex=True)
products['price'].replace(to_replace=r",", value='.', inplace=True, regex=True)
products['price'].replace(to_replace=r'R\$', value='', inplace=True, regex=True)

In [11]:
products = products.loc[products['price'] != 'X', :]

In [12]:
products['price'] = products['price'].astype('float32')

C:\Users\gulia\AppData\Local\Temp\ipykernel_8488\1828186873.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  products['preco'] = products['preco'].astype('float32')

In [14]:
products.reset_index(drop=True, inplace=True)
products = products.reset_index().rename(columns={'index': 'id_product'})
products['price'] = products['price'].round(decimals=2)
print(products.shape)

(399, 4)

,id_produto,nome,categoria,preco
0,0,"Processador AMD Ryzen 5 PRO 4650G, 6-Core, 12-...",amd,1599.900024
1,1,"Processador AMD Athlon Silver PRO 3125GE, 2-Co...",amd,699.900024
2,2,"Processador AMD Ryzen 3 PRO 4350G, 4-Core, 8-T...",amd,1199.000000
3,3,"Processador AMD Ryzen Threadripper PRO 3995WX,...",amd,35399.910156
4,4,"Processador AMD Ryzen 7 5700G, 8-Core, 16-Thre...",amd,2042.900024

In [15]:
len_products = len(products) - 1
print(len_products)

398

In [16]:
mun = pd.read_excel('cities_brazil.xlsx')

,IBGE,IBGE7,UF,Município,Região,População 2010,Porte,Capital
0,110001,1100015,RO,Alta Floresta D´oeste,Região Norte,24392.0,Pequeno II,NaN
1,110002,1100023,RO,Ariquemes,Região Norte,90353.0,Médio,NaN
2,110003,1100031,RO,Cabixi,Região Norte,6313.0,Pequeno I,NaN
3,110004,1100049,RO,Cacoal,Região Norte,78574.0,Médio,NaN
4,110005,1100056,RO,Cerejeiras,Região Norte,17029.0,Pequeno I,NaN

In [17]:
mun['prob'] = mun['População 2010'] / mun['População 2010'].sum()

,IBGE,IBGE7,UF,Município,Região,População 2010,Porte,Capital,prob
0,110001,1100015,RO,Alta Floresta D´oeste,Região Norte,24392.0,Pequeno II,NaN,0.000128
1,110002,1100023,RO,Ariquemes,Região Norte,90353.0,Médio,NaN,0.000474
2,110003,1100031,RO,Cabixi,Região Norte,6313.0,Pequeno I,NaN,0.000033
3,110004,1100049,RO,Cacoal,Região Norte,78574.0,Médio,NaN,0.000412
4,110005,1100056,RO,Cerejeiras,Região Norte,17029.0,Pequeno I,NaN,0.000089

In [19]:
import random
from random import randint
random.seed(123)
np.random.seed(123)

orders_dfs = []
orders_products_dfs = []

for i in it.chain(range(0, 2027), range(2027, 2900), range(2900, 4870), range(4870, 7026), range(7026, 8390), range(8390, 10039)):
    
    # generate data for orders table
    order_id = i
    
    # month
    if i <= 2026:
        month = '1-January'
    elif i <= 2899:
        month = '2-February'
    elif i <= 4868:
        month = '3-March'
    elif i <= 7025:
        month = '4-April'
    elif i <= 8389:
        month = '5-May'
    else:
        month = '6-June'
    
    local_df = mun.sample(1, weights=mun['prob'], axis=0)
    city = local_df['Município'].values[0]
    state = local_df['UF'].values[0]
    region = local_df['Região'].values[0]
    
    # quantity of products of order
    qt_products = randint(1, 10)
    
    # generate variable time_to_separate from normal distributions
    if qt_products <= 2:
        time_to_separate = np.random.normal(loc=4, scale=1, size=1)[0]
    elif qt_products <= 4:
        time_to_separate = np.random.normal(loc=8, scale=1, size=1)[0]
    elif qt_products <= 7:
        time_to_separate = np.random.normal(loc=14, scale=1, size=1)[0]
    else:
        time_to_separate = np.random.normal(loc=20, scale=1, size=1)[0]
        
    o = {'id_order': order_id, 'month': month, 'city': city, 'state': state, 'region': region, 'time_separate': time_to_separate}
    order_df = pd.DataFrame(data=o, index=[i])
    orders_dfs.append(order_df)
        
    # orders_products table data
    order_id_list = [i] * qt_products
    order_products_list = np.random.randint(0, high=len_products, size=qt_products)
    num_prod = [1, 2, 3, 4, 5]
    products_qt = np.random.choice(num_prod, qt_products, p=[0.8, 0.1, 0.05, 0.025, 0.025])

    op = {'id_order': order_id_list, 'id_product': order_products_list, 'quantity': products_qt}
    order_product_df = pd.DataFrame(data=op)
    orders_products_dfs.append(order_product_df)

orders = pd.concat(orders_dfs).reset_index(drop=True)
orders_products = pd.concat(orders_products_dfs).reset_index(drop=True)

In [29]:
print("Products: ", products.shape)
print("Orders: ", orders.shape)
print("Orders Products: ", orders_products.shape)

Products:  (399, 4)
Orders:  (10039, 6)
Orders Products:  (55086, 3)

In [23]:
products.to_excel('pichau_products.xlsx', index=False)
orders.to_excel('pichau_orders.xlsx', index=False)
orders_products.to_excel('pichau_orders_products.xlsx', index=False)

In [22]:
from sqlalchemy import create_engine

postgres_engine = create_engine('postgresql://postgres:postgres@postgres:5432/pichau', echo=True)

In [23]:
with postgres_engine.connect() as connection:
    result = connection.execute("select * from products limit 5")
    for row in result:
        print(row)

2022-03-08 17:46:26,991 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2022-03-08 17:46:26,992 INFO sqlalchemy.engine.Engine [raw sql] {}
2022-03-08 17:46:26,996 INFO sqlalchemy.engine.Engine select current_schema()
2022-03-08 17:46:26,996 INFO sqlalchemy.engine.Engine [raw sql] {}
2022-03-08 17:46:27,000 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2022-03-08 17:46:27,001 INFO sqlalchemy.engine.Engine [raw sql] {}
2022-03-08 17:46:27,004 INFO sqlalchemy.engine.Engine select * from products limit 5
2022-03-08 17:46:27,005 INFO sqlalchemy.engine.Engine [raw sql] {}

In [24]:
products.to_sql('products', con=postgres_engine, if_exists='replace')

2022-03-08 17:46:30,827 INFO sqlalchemy.engine.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2022-03-08 17:46:30,828 INFO sqlalchemy.engine.Engine [generated in 0.00144s] {'name': 'products'}
2022-03-08 17:46:30,836 INFO sqlalchemy.engine.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2022-03-08 17:46:30,836 INFO sqlalchemy.engine.Engine [cached since 0.009847s ago] {'name': 'products'}
2022-03-08 17:46:30,842 INFO sqlalchemy.engine.Engine SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = %(schema)s AND c.relkind in ('r', 'p')
2022-03-08 17:46:30,843 INFO sqlalchemy.engine.Engine [generated in 0.00084s] {'schema': 'public'}
2022-03-08 17:46:30,847 INFO sqlalchemy.engine.Engine
            SELECT c.oid
            FROM pg_catalog.pg_class c
            LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE (pg_catalog.pg_table_is_visible(c.oid))
            AND c.relname = %(table_name)s AND c.relkind in
            ('r', 'v', 'm', 'f', 'p')

2022-03-08 17:46:30,848 INFO sqlalchemy.engine.Engine [generated in 0.00058s] {'table_name': 'products'}
2022-03-08 17:46:30,851 INFO sqlalchemy.engine.Engine
            SELECT a.attname,
              pg_catalog.format_type(a.atttypid, a.atttypmod),
              (
                SELECT pg_catalog.pg_get_expr(d.adbin, d.adrelid)
                FROM pg_catalog.pg_attrdef d
                WHERE d.adrelid = a.attrelid AND d.adnum = a.attnum
                AND a.atthasdef
              ) AS DEFAULT,
              a.attnotnull,
              a.attrelid as table_oid,
              pgd.description as comment,
              a.attgenerated as generated,
                              (SELECT json_build_object(
                    'always', a.attidentity = 'a',
                    'start', s.seqstart,
                    'increment', s.seqincrement,
                    'minvalue', s.seqmin,
                    'maxvalue', s.seqmax,
                    'cache', s.seqcache,
                    'cycle', s.seqcycle)
                FROM pg_catalog.pg_sequence s
                JOIN pg_catalog.pg_class c on s.seqrelid = c."oid"
                WHERE c.relkind = 'S'
                AND a.attidentity != ''
                AND s.seqrelid = pg_catalog.pg_get_serial_sequence(
                    a.attrelid::regclass::text, a.attname
                )::regclass::oid
                ) as identity_options
            FROM pg_catalog.pg_attribute a
            LEFT JOIN pg_catalog.pg_description pgd ON (
                pgd.objoid = a.attrelid AND pgd.objsubid = a.attnum)
            WHERE a.attrelid = %(table_oid)s
            AND a.attnum > 0 AND NOT a.attisdropped
            ORDER BY a.attnum

2022-03-08 17:46:30,852 INFO sqlalchemy.engine.Engine [generated in 0.00071s] {'table_oid': 16385}
2022-03-08 17:46:30,863 INFO sqlalchemy.engine.Engine
            SELECT t.typname as "name",
               pg_catalog.format_type(t.typbasetype, t.typtypmod) as "attype",
               not t.typnotnull as "nullable",
               t.typdefault as "default",
               pg_catalog.pg_type_is_visible(t.oid) as "visible",
               n.nspname as "schema"
            FROM pg_catalog.pg_type t
               LEFT JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
            WHERE t.typtype = 'd'

2022-03-08 17:46:30,864 INFO sqlalchemy.engine.Engine [generated in 0.00071s] {}
2022-03-08 17:46:30,868 INFO sqlalchemy.engine.Engine
            SELECT t.typname as "name",
               -- no enum defaults in 8.4 at least
               -- t.typdefault as "default",
               pg_catalog.pg_type_is_visible(t.oid) as "visible",
               n.nspname as "schema",
               e.enumlabel as "label"
            FROM pg_catalog.pg_type t
                 LEFT JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
                 LEFT JOIN pg_catalog.pg_enum e ON t.oid = e.enumtypid
            WHERE t.typtype = 'e'
        ORDER BY "schema", "name", e.oid
2022-03-08 17:46:30,869 INFO sqlalchemy.engine.Engine [generated in 0.00055s] {}
2022-03-08 17:46:30,873 INFO sqlalchemy.engine.Engine
                SELECT a.attname
                FROM pg_attribute a JOIN (
                    SELECT unnest(ix.indkey) attnum,
                           generate_subscripts(ix.indkey, 1) ord
                    FROM pg_index ix
                    WHERE ix.indrelid = %(table_oid)s AND ix.indisprimary
                    ) k ON a.attnum=k.attnum
                WHERE a.attrelid = %(table_oid)s
                ORDER BY k.ord

2022-03-08 17:46:30,874 INFO sqlalchemy.engine.Engine [generated in 0.00082s] {'table_oid': 16385}
2022-03-08 17:46:30,879 INFO sqlalchemy.engine.Engine
        SELECT conname
           FROM  pg_catalog.pg_constraint r
           WHERE r.conrelid = %(table_oid)s AND r.contype = 'p'
           ORDER BY 1

2022-03-08 17:46:30,880 INFO sqlalchemy.engine.Engine [generated in 0.00092s] {'table_oid': 16385}
2022-03-08 17:46:30,887 INFO sqlalchemy.engine.Engine
          SELECT r.conname,
                pg_catalog.pg_get_constraintdef(r.oid, true) as condef,
                n.nspname as conschema
          FROM  pg_catalog.pg_constraint r,
                pg_namespace n,
                pg_class c

          WHERE r.conrelid = %(table)s AND
                r.contype = 'f' AND
                c.oid = confrelid AND
                n.oid = c.relnamespace
          ORDER BY 1

2022-03-08 17:46:30,888 INFO sqlalchemy.engine.Engine [generated in 0.00099s] {'table': 16385}
2022-03-08 17:46:30,892 INFO sqlalchemy.engine.Engine
              SELECT
                  i.relname as relname,
                  ix.indisunique, ix.indexprs,
                  a.attname, a.attnum, c.conrelid, ix.indkey::varchar,
                  ix.indoption::varchar, i.reloptions, am.amname,
                  pg_get_expr(ix.indpred, ix.indrelid),
                  ix.indnkeyatts as indnkeyatts
              FROM
                  pg_class t
                        join pg_index ix on t.oid = ix.indrelid
                        join pg_class i on i.oid = ix.indexrelid
                        left outer join
                            pg_attribute a
                            on t.oid = a.attrelid and a.attnum = ANY(ix.indkey)
                        left outer join
                            pg_constraint c
                            on (ix.indrelid = c.conrelid and
                                ix.indexrelid = c.conindid and
                                c.contype in ('p', 'u', 'x'))
                        left outer join
                            pg_am am
                            on i.relam = am.oid
              WHERE
                  t.relkind IN ('r', 'v', 'f', 'm', 'p')
                  and t.oid = %(table_oid)s
                  and ix.indisprimary = 'f'
              ORDER BY
                  t.relname,
                  i.relname

2022-03-08 17:46:30,893 INFO sqlalchemy.engine.Engine [generated in 0.00077s] {'table_oid': 16385}
2022-03-08 17:46:30,899 INFO sqlalchemy.engine.Engine
            SELECT
                cons.conname as name,
                cons.conkey as key,
                a.attnum as col_num,
                a.attname as col_name
            FROM
                pg_catalog.pg_constraint cons
                join pg_attribute a
                  on cons.conrelid = a.attrelid AND
                    a.attnum = ANY(cons.conkey)
            WHERE
                cons.conrelid = %(table_oid)s AND
                cons.contype = 'u'

2022-03-08 17:46:30,900 INFO sqlalchemy.engine.Engine [generated in 0.00080s] {'table_oid': 16385}
2022-03-08 17:46:30,902 INFO sqlalchemy.engine.Engine
            SELECT
                cons.conname as name,
                pg_get_constraintdef(cons.oid) as src
            FROM
                pg_catalog.pg_constraint cons
            WHERE
                cons.conrelid = %(table_oid)s AND
                cons.contype = 'c'

2022-03-08 17:46:30,903 INFO sqlalchemy.engine.Engine [generated in 0.00079s] {'table_oid': 16385}
2022-03-08 17:46:30,905 INFO sqlalchemy.engine.Engine
            SELECT
                pgd.description as table_comment
            FROM
                pg_catalog.pg_description pgd
            WHERE
                pgd.objsubid = 0 AND
                pgd.objoid = %(table_oid)s

2022-03-08 17:46:30,906 INFO sqlalchemy.engine.Engine [generated in 0.00056s] {'table_oid': 16385}
2022-03-08 17:46:30,909 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-03-08 17:46:30,909 INFO sqlalchemy.engine.Engine
DROP TABLE products
2022-03-08 17:46:30,910 INFO sqlalchemy.engine.Engine [no key 0.00070s] {}
2022-03-08 17:46:30,917 INFO sqlalchemy.engine.Engine COMMIT
2022-03-08 17:46:30,920 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-03-08 17:46:30,922 INFO sqlalchemy.engine.Engine
CREATE TABLE products (
	index BIGINT,
	id_produto BIGINT,
	nome TEXT,
	categoria TEXT,
	preco FLOAT(23)
)


2022-03-08 17:46:30,922 INFO sqlalchemy.engine.Engine [no key 0.00079s] {}
2022-03-08 17:46:30,936 INFO sqlalchemy.engine.Engine CREATE INDEX ix_products_index ON products (index)
2022-03-08 17:46:30,937 INFO sqlalchemy.engine.Engine [no key 0.00059s] {}
2022-03-08 17:46:30,940 INFO sqlalchemy.engine.Engine COMMIT
2022-03-08 17:46:30,944 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-03-08 17:46:30,947 INFO sqlalchemy.engine.Engine INSERT INTO products (index, id_produto, nome, categoria, preco) VALUES (%(index)s, %(id_produto)s, %(nome)s, %(categoria)s, %(preco)s)
2022-03-08 17:46:30,948 INFO sqlalchemy.engine.Engine [generated in 0.00226s] ({'index': 0, 'id_produto': 0, 'nome': 'Processador AMD Ryzen 5 PRO 4650G, 6-Core, 12-Threads, 3.7GHz (4.2GHz Turbo), Cache 8MB, AM4, 100-100000143MPK', 'categoria': 'amd', 'preco': 1599.9000244140625}, {'index': 1, 'id_produto': 1, 'nome': 'Processador AMD Athlon Silver PRO 3125GE, 2-Core, 4-Threads, 3.4GHz, Cache 5MB, AM4, YD3125C6M2OFH-OEM', 'categoria': 'amd', 'preco': 699.9000244140625}, {'index': 2, 'id_produto': 2, 'nome': 'Processador AMD Ryzen 3 PRO 4350G, 4-Core, 8-Threads, 3.8GHz (4.0GHz Turbo), Cache 6MB, AM4, 100-000000148OEM', 'categoria': 'amd', 'preco': 1199.0}, {'index': 3, 'id_produto': 3, 'nome': 'Processador AMD Ryzen Threadripper PRO 3995WX, 64-Core, 128-Threads, 2.7GHz (4.2GHz Turbo), Cache 288MB, sWRX8, 100-100000087WOF', 'categoria': 'amd', 'preco': 35399.91015625}, {'index': 4, 'id_produto': 4, 'nome': 'Processador AMD Ryzen 7 5700G, 8-Core, 16-Threads, 3.8GHz (4.6GHz Turbo), Cache 20MB, AM4, 100-100000263BOX', 'categoria': 'amd', 'preco': 2042.9000244140625}, {'index': 5, 'id_produto': 5, 'nome': 'Processador AMD Ryzen 5 5600G, 6-Core, 12-Threads, 3.9GHz (4.4GHz Turbo), Cache 19MB, AM4, 100-100000252BOX', 'categoria': 'amd', 'preco': 1592.9000244140625}, {'index': 6, 'id_produto': 6, 'nome': 'Processador AMD Ryzen Threadripper PRO 3975WX, 32-Core, 64-Threads, 3.5GHz (4.2GHz Turbo), Cache 144MB, sWRX8, 100-100000086WOF', 'categoria': 'amd', 'preco': 20321.880859375}, {'index': 7, 'id_produto': 7, 'nome': 'Processador AMD Ryzen 9 5950X, 16-Core, 32-Threads, 3.4GHz (4.9GHz Turbo), Cache 72MB, AM4, 100-100000059WOF', 'categoria': 'amd', 'preco': 4442.89990234375}  ... displaying 10 of 399 total bound parameter sets ...  {'index': 397, 'id_produto': 397, 'nome': "Monitor Gamer Asus 23,8'' LED 1ms 144hz Ips FreeSync Premium HDMI/DP, VP249QGR", 'categoria': 'monitores', 'preco': 1849.9599609375}, {'index': 398, 'id_produto': 398, 'nome': 'Monitor Gamer Asus 27 Pol. 5ms 75Hz FreeSync HDMI/VGA, VA27EHE', 'categoria': 'monitores', 'preco': 2169.070068359375})
2022-03-08 17:46:30,959 INFO sqlalchemy.engine.Engine COMMIT

399

In [25]:
orders.to_sql('orders', con=postgres_engine, if_exists='replace')

2022-03-08 17:46:38,542 INFO sqlalchemy.engine.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2022-03-08 17:46:38,543 INFO sqlalchemy.engine.Engine [cached since 7.717s ago] {'name': 'orders'}
2022-03-08 17:46:38,549 INFO sqlalchemy.engine.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2022-03-08 17:46:38,549 INFO sqlalchemy.engine.Engine [cached since 7.723s ago] {'name': 'orders'}
2022-03-08 17:46:38,554 INFO sqlalchemy.engine.Engine SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = %(schema)s AND c.relkind in ('r', 'p')
2022-03-08 17:46:38,555 INFO sqlalchemy.engine.Engine [cached since 7.713s ago] {'schema': 'public'}
2022-03-08 17:46:38,558 INFO sqlalchemy.engine.Engine
            SELECT c.oid
            FROM pg_catalog.pg_class c
            LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE (pg_catalog.pg_table_is_visible(c.oid))
            AND c.relname = %(table_name)s AND c.relkind in
            ('r', 'v', 'm', 'f', 'p')

2022-03-08 17:46:38,559 INFO sqlalchemy.engine.Engine [cached since 7.712s ago] {'table_name': 'orders'}
2022-03-08 17:46:38,561 INFO sqlalchemy.engine.Engine
            SELECT a.attname,
              pg_catalog.format_type(a.atttypid, a.atttypmod),
              (
                SELECT pg_catalog.pg_get_expr(d.adbin, d.adrelid)
                FROM pg_catalog.pg_attrdef d
                WHERE d.adrelid = a.attrelid AND d.adnum = a.attnum
                AND a.atthasdef
              ) AS DEFAULT,
              a.attnotnull,
              a.attrelid as table_oid,
              pgd.description as comment,
              a.attgenerated as generated,
                              (SELECT json_build_object(
                    'always', a.attidentity = 'a',
                    'start', s.seqstart,
                    'increment', s.seqincrement,
                    'minvalue', s.seqmin,
                    'maxvalue', s.seqmax,
                    'cache', s.seqcache,
                    'cycle', s.seqcycle)
                FROM pg_catalog.pg_sequence s
                JOIN pg_catalog.pg_class c on s.seqrelid = c."oid"
                WHERE c.relkind = 'S'
                AND a.attidentity != ''
                AND s.seqrelid = pg_catalog.pg_get_serial_sequence(
                    a.attrelid::regclass::text, a.attname
                )::regclass::oid
                ) as identity_options
            FROM pg_catalog.pg_attribute a
            LEFT JOIN pg_catalog.pg_description pgd ON (
                pgd.objoid = a.attrelid AND pgd.objsubid = a.attnum)
            WHERE a.attrelid = %(table_oid)s
            AND a.attnum > 0 AND NOT a.attisdropped
            ORDER BY a.attnum

2022-03-08 17:46:38,562 INFO sqlalchemy.engine.Engine [cached since 7.711s ago] {'table_oid': 16392}
2022-03-08 17:46:38,564 INFO sqlalchemy.engine.Engine
            SELECT t.typname as "name",
               pg_catalog.format_type(t.typbasetype, t.typtypmod) as "attype",
               not t.typnotnull as "nullable",
               t.typdefault as "default",
               pg_catalog.pg_type_is_visible(t.oid) as "visible",
               n.nspname as "schema"
            FROM pg_catalog.pg_type t
               LEFT JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
            WHERE t.typtype = 'd'

2022-03-08 17:46:38,565 INFO sqlalchemy.engine.Engine [cached since 7.702s ago] {}
2022-03-08 17:46:38,567 INFO sqlalchemy.engine.Engine
            SELECT t.typname as "name",
               -- no enum defaults in 8.4 at least
               -- t.typdefault as "default",
               pg_catalog.pg_type_is_visible(t.oid) as "visible",
               n.nspname as "schema",
               e.enumlabel as "label"
            FROM pg_catalog.pg_type t
                 LEFT JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
                 LEFT JOIN pg_catalog.pg_enum e ON t.oid = e.enumtypid
            WHERE t.typtype = 'e'
        ORDER BY "schema", "name", e.oid
2022-03-08 17:46:38,567 INFO sqlalchemy.engine.Engine [cached since 7.7s ago] {}
2022-03-08 17:46:38,571 INFO sqlalchemy.engine.Engine
                SELECT a.attname
                FROM pg_attribute a JOIN (
                    SELECT unnest(ix.indkey) attnum,
                           generate_subscripts(ix.indkey, 1) ord
                    FROM pg_index ix
                    WHERE ix.indrelid = %(table_oid)s AND ix.indisprimary
                    ) k ON a.attnum=k.attnum
                WHERE a.attrelid = %(table_oid)s
                ORDER BY k.ord

2022-03-08 17:46:38,572 INFO sqlalchemy.engine.Engine [cached since 7.699s ago] {'table_oid': 16392}
2022-03-08 17:46:38,574 INFO sqlalchemy.engine.Engine
        SELECT conname
           FROM  pg_catalog.pg_constraint r
           WHERE r.conrelid = %(table_oid)s AND r.contype = 'p'
           ORDER BY 1

2022-03-08 17:46:38,575 INFO sqlalchemy.engine.Engine [cached since 7.696s ago] {'table_oid': 16392}
2022-03-08 17:46:38,577 INFO sqlalchemy.engine.Engine
          SELECT r.conname,
                pg_catalog.pg_get_constraintdef(r.oid, true) as condef,
                n.nspname as conschema
          FROM  pg_catalog.pg_constraint r,
                pg_namespace n,
                pg_class c

          WHERE r.conrelid = %(table)s AND
                r.contype = 'f' AND
                c.oid = confrelid AND
                n.oid = c.relnamespace
          ORDER BY 1

2022-03-08 17:46:38,578 INFO sqlalchemy.engine.Engine [cached since 7.692s ago] {'table': 16392}
2022-03-08 17:46:38,580 INFO sqlalchemy.engine.Engine
              SELECT
                  i.relname as relname,
                  ix.indisunique, ix.indexprs,
                  a.attname, a.attnum, c.conrelid, ix.indkey::varchar,
                  ix.indoption::varchar, i.reloptions, am.amname,
                  pg_get_expr(ix.indpred, ix.indrelid),
                  ix.indnkeyatts as indnkeyatts
              FROM
                  pg_class t
                        join pg_index ix on t.oid = ix.indrelid
                        join pg_class i on i.oid = ix.indexrelid
                        left outer join
                            pg_attribute a
                            on t.oid = a.attrelid and a.attnum = ANY(ix.indkey)
                        left outer join
                            pg_constraint c
                            on (ix.indrelid = c.conrelid and
                                ix.indexrelid = c.conindid and
                                c.contype in ('p', 'u', 'x'))
                        left outer join
                            pg_am am
                            on i.relam = am.oid
              WHERE
                  t.relkind IN ('r', 'v', 'f', 'm', 'p')
                  and t.oid = %(table_oid)s
                  and ix.indisprimary = 'f'
              ORDER BY
                  t.relname,
                  i.relname

2022-03-08 17:46:38,581 INFO sqlalchemy.engine.Engine [cached since 7.689s ago] {'table_oid': 16392}
2022-03-08 17:46:38,584 INFO sqlalchemy.engine.Engine
            SELECT
                cons.conname as name,
                cons.conkey as key,
                a.attnum as col_num,
                a.attname as col_name
            FROM
                pg_catalog.pg_constraint cons
                join pg_attribute a
                  on cons.conrelid = a.attrelid AND
                    a.attnum = ANY(cons.conkey)
            WHERE
                cons.conrelid = %(table_oid)s AND
                cons.contype = 'u'

2022-03-08 17:46:38,585 INFO sqlalchemy.engine.Engine [cached since 7.686s ago] {'table_oid': 16392}
2022-03-08 17:46:38,588 INFO sqlalchemy.engine.Engine
            SELECT
                cons.conname as name,
                pg_get_constraintdef(cons.oid) as src
            FROM
                pg_catalog.pg_constraint cons
            WHERE
                cons.conrelid = %(table_oid)s AND
                cons.contype = 'c'

2022-03-08 17:46:38,588 INFO sqlalchemy.engine.Engine [cached since 7.686s ago] {'table_oid': 16392}
2022-03-08 17:46:38,590 INFO sqlalchemy.engine.Engine
            SELECT
                pgd.description as table_comment
            FROM
                pg_catalog.pg_description pgd
            WHERE
                pgd.objsubid = 0 AND
                pgd.objoid = %(table_oid)s

2022-03-08 17:46:38,591 INFO sqlalchemy.engine.Engine [cached since 7.686s ago] {'table_oid': 16392}
2022-03-08 17:46:38,593 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-03-08 17:46:38,594 INFO sqlalchemy.engine.Engine
DROP TABLE orders
2022-03-08 17:46:38,595 INFO sqlalchemy.engine.Engine [no key 0.00073s] {}
2022-03-08 17:46:38,598 INFO sqlalchemy.engine.Engine COMMIT
2022-03-08 17:46:38,603 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-03-08 17:46:38,604 INFO sqlalchemy.engine.Engine
CREATE TABLE orders (
	index BIGINT,
	id_pedido BIGINT,
	mes TEXT,
	cidade TEXT,
	uf TEXT,
	regiao TEXT,
	tempo_separacao FLOAT(53)
)


2022-03-08 17:46:38,605 INFO sqlalchemy.engine.Engine [no key 0.00061s] {}
2022-03-08 17:46:38,610 INFO sqlalchemy.engine.Engine CREATE INDEX ix_orders_index ON orders (index)
2022-03-08 17:46:38,610 INFO sqlalchemy.engine.Engine [no key 0.00065s] {}
2022-03-08 17:46:38,614 INFO sqlalchemy.engine.Engine COMMIT
2022-03-08 17:46:38,621 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-03-08 17:46:38,688 INFO sqlalchemy.engine.Engine INSERT INTO orders (index, id_pedido, mes, cidade, uf, regiao, tempo_separacao) VALUES (%(index)s, %(id_pedido)s, %(mes)s, %(cidade)s, %(uf)s, %(regiao)s, %(tempo_separacao)s)
2022-03-08 17:46:38,689 INFO sqlalchemy.engine.Engine [generated in 0.05381s] ({'index': 0, 'id_pedido': 0, 'mes': '1-Janeiro', 'cidade': 'São Carlos', 'uf': 'SP', 'regiao': 'Região Sudeste', 'tempo_separacao': 3.047902793138678}, {'index': 1, 'id_pedido': 1, 'mes': '1-Janeiro', 'cidade': 'Campos Dos Goytacazes', 'uf': 'RJ', 'regiao': 'Região Sudeste', 'tempo_separacao': 13.254558940517342}, {'index': 2, 'id_pedido': 2, 'mes': '1-Janeiro', 'cidade': 'Novo Repartimento', 'uf': 'PA', 'regiao': 'Região Norte', 'tempo_separacao': 5.491389626124288}, {'index': 3, 'id_pedido': 3, 'mes': '1-Janeiro', 'cidade': 'Nova Era', 'uf': 'MG', 'regiao': 'Região Sudeste', 'tempo_separacao': 13.361098003315348}, {'index': 4, 'id_pedido': 4, 'mes': '1-Janeiro', 'cidade': 'Parintins', 'uf': 'AM', 'regiao': 'Região Norte', 'tempo_separacao': 13.67305377290264}, {'index': 5, 'id_pedido': 5, 'mes': '1-Janeiro', 'cidade': 'São José', 'uf': 'SC', 'regiao': 'Região Sul', 'tempo_separacao': 3.6917908037833613}, {'index': 6, 'id_pedido': 6, 'mes': '1-Janeiro', 'cidade': 'Poços de Caldas', 'uf': 'MG', 'regiao': 'Região Sudeste', 'tempo_separacao': 3.87470147054903}, {'index': 7, 'id_pedido': 7, 'mes': '1-Janeiro', 'cidade': 'Patrocínio', 'uf': 'MG', 'regiao': 'Região Sudeste', 'tempo_separacao': 15.649475521426908}  ... displaying 10 of 10039 total bound parameter sets ...  {'index': 10037, 'id_pedido': 10037, 'mes': '6-Junho', 'cidade': 'Valparaíso de Goiás', 'uf': 'GO', 'regiao': 'Região Centro-Oeste', 'tempo_separacao': 13.40339472143366}, {'index': 10038, 'id_pedido': 10038, 'mes': '6-Junho', 'cidade': 'Campos Dos Goytacazes', 'uf': 'RJ', 'regiao': 'Região Sudeste', 'tempo_separacao': 12.97032044454782})
2022-03-08 17:46:39,062 INFO sqlalchemy.engine.Engine COMMIT

39

In [26]:
orders_products.to_sql('orders_products', con=postgres_engine, if_exists='replace')

2022-03-08 17:46:47,427 INFO sqlalchemy.engine.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2022-03-08 17:46:47,428 INFO sqlalchemy.engine.Engine [cached since 16.6s ago] {'name': 'orders_products'}
2022-03-08 17:46:47,434 INFO sqlalchemy.engine.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2022-03-08 17:46:47,435 INFO sqlalchemy.engine.Engine [cached since 16.61s ago] {'name': 'orders_products'}
2022-03-08 17:46:47,440 INFO sqlalchemy.engine.Engine SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = %(schema)s AND c.relkind in ('r', 'p')
2022-03-08 17:46:47,440 INFO sqlalchemy.engine.Engine [cached since 16.6s ago] {'schema': 'public'}
2022-03-08 17:46:47,443 INFO sqlalchemy.engine.Engine
            SELECT c.oid
            FROM pg_catalog.pg_class c
            LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE (pg_catalog.pg_table_is_visible(c.oid))
            AND c.relname = %(table_name)s AND c.relkind in
            ('r', 'v', 'm', 'f', 'p')

2022-03-08 17:46:47,444 INFO sqlalchemy.engine.Engine [cached since 16.6s ago] {'table_name': 'orders_products'}
2022-03-08 17:46:47,446 INFO sqlalchemy.engine.Engine
            SELECT a.attname,
              pg_catalog.format_type(a.atttypid, a.atttypmod),
              (
                SELECT pg_catalog.pg_get_expr(d.adbin, d.adrelid)
                FROM pg_catalog.pg_attrdef d
                WHERE d.adrelid = a.attrelid AND d.adnum = a.attnum
                AND a.atthasdef
              ) AS DEFAULT,
              a.attnotnull,
              a.attrelid as table_oid,
              pgd.description as comment,
              a.attgenerated as generated,
                              (SELECT json_build_object(
                    'always', a.attidentity = 'a',
                    'start', s.seqstart,
                    'increment', s.seqincrement,
                    'minvalue', s.seqmin,
                    'maxvalue', s.seqmax,
                    'cache', s.seqcache,
                    'cycle', s.seqcycle)
                FROM pg_catalog.pg_sequence s
                JOIN pg_catalog.pg_class c on s.seqrelid = c."oid"
                WHERE c.relkind = 'S'
                AND a.attidentity != ''
                AND s.seqrelid = pg_catalog.pg_get_serial_sequence(
                    a.attrelid::regclass::text, a.attname
                )::regclass::oid
                ) as identity_options
            FROM pg_catalog.pg_attribute a
            LEFT JOIN pg_catalog.pg_description pgd ON (
                pgd.objoid = a.attrelid AND pgd.objsubid = a.attnum)
            WHERE a.attrelid = %(table_oid)s
            AND a.attnum > 0 AND NOT a.attisdropped
            ORDER BY a.attnum

2022-03-08 17:46:47,447 INFO sqlalchemy.engine.Engine [cached since 16.6s ago] {'table_oid': 16399}
2022-03-08 17:46:47,449 INFO sqlalchemy.engine.Engine
            SELECT t.typname as "name",
               pg_catalog.format_type(t.typbasetype, t.typtypmod) as "attype",
               not t.typnotnull as "nullable",
               t.typdefault as "default",
               pg_catalog.pg_type_is_visible(t.oid) as "visible",
               n.nspname as "schema"
            FROM pg_catalog.pg_type t
               LEFT JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
            WHERE t.typtype = 'd'

2022-03-08 17:46:47,449 INFO sqlalchemy.engine.Engine [cached since 16.59s ago] {}
2022-03-08 17:46:47,452 INFO sqlalchemy.engine.Engine
            SELECT t.typname as "name",
               -- no enum defaults in 8.4 at least
               -- t.typdefault as "default",
               pg_catalog.pg_type_is_visible(t.oid) as "visible",
               n.nspname as "schema",
               e.enumlabel as "label"
            FROM pg_catalog.pg_type t
                 LEFT JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
                 LEFT JOIN pg_catalog.pg_enum e ON t.oid = e.enumtypid
            WHERE t.typtype = 'e'
        ORDER BY "schema", "name", e.oid
2022-03-08 17:46:47,452 INFO sqlalchemy.engine.Engine [cached since 16.58s ago] {}
2022-03-08 17:46:47,455 INFO sqlalchemy.engine.Engine
                SELECT a.attname
                FROM pg_attribute a JOIN (
                    SELECT unnest(ix.indkey) attnum,
                           generate_subscripts(ix.indkey, 1) ord
                    FROM pg_index ix
                    WHERE ix.indrelid = %(table_oid)s AND ix.indisprimary
                    ) k ON a.attnum=k.attnum
                WHERE a.attrelid = %(table_oid)s
                ORDER BY k.ord

2022-03-08 17:46:47,456 INFO sqlalchemy.engine.Engine [cached since 16.58s ago] {'table_oid': 16399}
2022-03-08 17:46:47,459 INFO sqlalchemy.engine.Engine
        SELECT conname
           FROM  pg_catalog.pg_constraint r
           WHERE r.conrelid = %(table_oid)s AND r.contype = 'p'
           ORDER BY 1

2022-03-08 17:46:47,459 INFO sqlalchemy.engine.Engine [cached since 16.58s ago] {'table_oid': 16399}
2022-03-08 17:46:47,462 INFO sqlalchemy.engine.Engine
          SELECT r.conname,
                pg_catalog.pg_get_constraintdef(r.oid, true) as condef,
                n.nspname as conschema
          FROM  pg_catalog.pg_constraint r,
                pg_namespace n,
                pg_class c

          WHERE r.conrelid = %(table)s AND
                r.contype = 'f' AND
                c.oid = confrelid AND
                n.oid = c.relnamespace
          ORDER BY 1

2022-03-08 17:46:47,462 INFO sqlalchemy.engine.Engine [cached since 16.58s ago] {'table': 16399}
2022-03-08 17:46:47,465 INFO sqlalchemy.engine.Engine
              SELECT
                  i.relname as relname,
                  ix.indisunique, ix.indexprs,
                  a.attname, a.attnum, c.conrelid, ix.indkey::varchar,
                  ix.indoption::varchar, i.reloptions, am.amname,
                  pg_get_expr(ix.indpred, ix.indrelid),
                  ix.indnkeyatts as indnkeyatts
              FROM
                  pg_class t
                        join pg_index ix on t.oid = ix.indrelid
                        join pg_class i on i.oid = ix.indexrelid
                        left outer join
                            pg_attribute a
                            on t.oid = a.attrelid and a.attnum = ANY(ix.indkey)
                        left outer join
                            pg_constraint c
                            on (ix.indrelid = c.conrelid and
                                ix.indexrelid = c.conindid and
                                c.contype in ('p', 'u', 'x'))
                        left outer join
                            pg_am am
                            on i.relam = am.oid
              WHERE
                  t.relkind IN ('r', 'v', 'f', 'm', 'p')
                  and t.oid = %(table_oid)s
                  and ix.indisprimary = 'f'
              ORDER BY
                  t.relname,
                  i.relname

2022-03-08 17:46:47,466 INFO sqlalchemy.engine.Engine [cached since 16.57s ago] {'table_oid': 16399}
2022-03-08 17:46:47,469 INFO sqlalchemy.engine.Engine
            SELECT
                cons.conname as name,
                cons.conkey as key,
                a.attnum as col_num,
                a.attname as col_name
            FROM
                pg_catalog.pg_constraint cons
                join pg_attribute a
                  on cons.conrelid = a.attrelid AND
                    a.attnum = ANY(cons.conkey)
            WHERE
                cons.conrelid = %(table_oid)s AND
                cons.contype = 'u'

2022-03-08 17:46:47,470 INFO sqlalchemy.engine.Engine [cached since 16.57s ago] {'table_oid': 16399}
2022-03-08 17:46:47,472 INFO sqlalchemy.engine.Engine
            SELECT
                cons.conname as name,
                pg_get_constraintdef(cons.oid) as src
            FROM
                pg_catalog.pg_constraint cons
            WHERE
                cons.conrelid = %(table_oid)s AND
                cons.contype = 'c'

2022-03-08 17:46:47,473 INFO sqlalchemy.engine.Engine [cached since 16.57s ago] {'table_oid': 16399}
2022-03-08 17:46:47,475 INFO sqlalchemy.engine.Engine
            SELECT
                pgd.description as table_comment
            FROM
                pg_catalog.pg_description pgd
            WHERE
                pgd.objsubid = 0 AND
                pgd.objoid = %(table_oid)s

2022-03-08 17:46:47,476 INFO sqlalchemy.engine.Engine [cached since 16.57s ago] {'table_oid': 16399}
2022-03-08 17:46:47,479 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-03-08 17:46:47,480 INFO sqlalchemy.engine.Engine
DROP TABLE orders_products
2022-03-08 17:46:47,481 INFO sqlalchemy.engine.Engine [no key 0.00087s] {}
2022-03-08 17:46:47,484 INFO sqlalchemy.engine.Engine COMMIT
2022-03-08 17:46:47,487 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-03-08 17:46:47,488 INFO sqlalchemy.engine.Engine
CREATE TABLE orders_products (
	index BIGINT,
	id_pedido BIGINT,
	id_produto INTEGER,
	quantidade INTEGER
)


2022-03-08 17:46:47,489 INFO sqlalchemy.engine.Engine [no key 0.00069s] {}
2022-03-08 17:46:47,492 INFO sqlalchemy.engine.Engine CREATE INDEX ix_orders_products_index ON orders_products (index)
2022-03-08 17:46:47,493 INFO sqlalchemy.engine.Engine [no key 0.00061s] {}
2022-03-08 17:46:47,496 INFO sqlalchemy.engine.Engine COMMIT
2022-03-08 17:46:47,503 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-03-08 17:46:47,708 INFO sqlalchemy.engine.Engine INSERT INTO orders_products (index, id_pedido, id_produto, quantidade) VALUES (%(index)s, %(id_pedido)s, %(id_produto)s, %(quantidade)s)
2022-03-08 17:46:47,709 INFO sqlalchemy.engine.Engine [generated in 0.17216s] ({'index': 0, 'id_pedido': 0, 'id_produto': 230, 'quantidade': 1}, {'index': 1, 'id_pedido': 1, 'id_produto': 57, 'quantidade': 1}, {'index': 2, 'id_pedido': 1, 'id_produto': 214, 'quantidade': 1}, {'index': 3, 'id_pedido': 1, 'id_produto': 225, 'quantidade': 1}, {'index': 4, 'id_pedido': 1, 'id_produto': 96, 'quantidade': 1}, {'index': 5, 'id_pedido': 1, 'id_produto': 113, 'quantidade': 1}, {'index': 6, 'id_pedido': 2, 'id_produto': 311, 'quantidade': 1}, {'index': 7, 'id_pedido': 2, 'id_produto': 2, 'quantidade': 1}  ... displaying 10 of 55086 total bound parameter sets ...  {'index': 55084, 'id_pedido': 10038, 'id_produto': 108, 'quantidade': 1}, {'index': 55085, 'id_pedido': 10038, 'id_produto': 196, 'quantidade': 1})
2022-03-08 17:46:49,188 INFO sqlalchemy.engine.Engine COMMIT

86

In [27]:
postgres_engine.dispose()

# --------------------------------